# development:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: scm_ativos
#   password: scm_ativos
#   host: localhost
#   schema_search_path: scm_ativos
#   database: db_desenv

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ativos-pge_development

test:
  <<: *default
  database: ativos-pge_test

production:
  <<: *default
  database: ativos-pge_production
  username: ativos-pge
  password: <%= ENV['ATIVOS-PGE_DATABASE_PASSWORD'] %>
